//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace broker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pointss
    {
        public int id { get; set; }
        public string points { get; set; }
        public string datee { get; set; }
        public string cus_id { get; set; }
    }
}
